//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letworldknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.AdvertisementApplication = new HashSet<AdvertisementApplication>();
            this.Document = new HashSet<Document>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string advertisement_title { get; set; }
        public string advertisement_description { get; set; }
        public Nullable<int> advertisement_type_id { get; set; }
        public string advertisement_price { get; set; }
        public Nullable<System.DateTime> advertisement_date { get; set; }
        public string advertisement_location { get; set; }
    
        public virtual AdvertisementType AdvertisementType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertisementApplication> AdvertisementApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
    }
}
