//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letworldknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int id { get; set; }
        public Nullable<int> giver_id { get; set; }
        public Nullable<int> recipient_id { get; set; }
        public Nullable<bool> request_status { get; set; }
        public Nullable<bool> follow_status { get; set; }
        public Nullable<bool> block_status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
